### ISSUE TITLE
feat: add Avatar component

### ISSUE THREAD

**Issue by kirandash** [kirandash/greenhouse-react-ui#5]
**Design:** 

![image](https://user-images.githubusercontent.com/13310363/236379489-dacb381d-b3ec-4ae3-829d-ccf9acf7b314.png)

<h2 id="props-overview" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); margin: 3rem 0px 1rem; font-size: 1.25rem; font-weight: 600; font-family: &quot;Fira Code&quot;, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; position: relative; --text-opacity:1; color: rgba(36,38,45,var(--text-opacity)); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Props overview</h2>

Prop | Description | Type | Default
-- | -- | -- | --
size | define the size of component | large, regular, small | regular
src | required define the src of the image | string |  
alt | required alternate text of the image | string |  

<h2 id="customizing" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); margin: 3rem 0px 1rem; font-size: 1.25rem; font-weight: 600; font-family: &quot;Fira Code&quot;, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; position: relative; --text-opacity:1; color: rgba(36,38,45,var(--text-opacity)); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a aria-hidden="true" tabindex="-1" href="https://windmillui.com/react-ui/components/avatar#customizing" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); background-color: transparent; color: inherit; text-decoration: inherit; position: absolute;"><span class="icon icon-link" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); width: 1rem; height: 1rem; background-image: url(&quot;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' fill='none' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' viewBox='0 0 24 24' stroke='currentColor'%3E%3Cpath d='M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1'%3E%3C/path%3E%3C/svg%3E&quot;); background-repeat: no-repeat;"></span></a></h2><br class="Apple-interchange-newline">

Requirements:
- [ ] `size` prop: there are three sizes, applied by the prop `size`: `large`, `regular` (default) and `small`.
For large: size should be 40px, regular should be 32px and small should be 24px
- [ ] Pass an image to the avatar using the prop `src`.
- [ ] Alternate text: Pass an alternate text to the avatar using the prop `alt`.
- [ ] Customisable: User should be able to pass their own class, style or other props to the element and it should be applied, please have a look at the other existing components to understand how it is done
- [ ] Add unit tests to test the above requirements, please have a look at tests written for other components

Ex: 
```
<Avatar size="large" src="https://i.pravatar.cc/300" alt="Judith" />
<Avatar src="https://i.pravatar.cc/300" alt="Judith" />
<Avatar size="small" src="/img/avatar-1.jpg" alt="Judith" />
```

**Comment by olakadasami** [comment]
Hello
I'd like to handle this issue

**Comment by kirandash** [comment]
> Hello
> 
> I'd like to handle this issue
> 
> 

Thanks @olakadasami 🙏 for showing your interest! I have now assigned the task to you.

If you need any help, you can comment here or reach me on discord at:

https://discord.gg/62VR3MMCVm

And if you like this project, please do show your support by leaving a star ⭐️ for more visibility

**Comment by olakadasami** [comment]
I reached out on discord about an error i had while pushing
![Screenshot (124)](https://github.com/kirandash/greenhouse-react-ui/assets/64378500/2bfe24a3-ca84-4513-9f76-be5094a5ac91)

**Comment by kirandash** [comment]
hello Olakada Samuel,

sorry for the late response. I missed your message on discord.

The error you are seeing is related to formatting.

To fix this issue: you can run the command npm run format

this will check for any format mismatch and format all your code. then if
you push your changes it will work Please do let me know if that doesn’t
work

**Comment by kirandash** [comment]
@olakadasami Thanks for your contribution 🙏

**Comment by olakadasami** [comment]
You're welcome
Thanks for the opportunity
