### ISSUE TITLE
feat: add Textarea component

### ISSUE THREAD

**Issue by kirandash** [kirandash/greenhouse-react-ui#6]
**Design:** (Please use the same styles that are already added for input component)

Base textarea:
![image](https://user-images.githubusercontent.com/13310363/236437719-fa42712f-8ed5-4141-81a2-191cda6bef41.png)

Disabled state for textarea:
![image](https://user-images.githubusercontent.com/13310363/236437418-4b1afb29-69e5-48d6-a0c8-e6dcb08d58a1.png)
Ex: 
`<Textarea disabled rows="3" placeholder="Enter some long form content." />`

Invalid state:
![image](https://user-images.githubusercontent.com/13310363/236437587-3d697577-31f3-43d8-b991-b27b083d5ee3.png)
Ex: 
`<Textarea invalid rows="3" placeholder="Enter some long form content." />`

Textarea with label: 
![image](https://user-images.githubusercontent.com/13310363/236436635-ed373a07-6d78-4537-ad95-54d4ba34e83f.png)
Ex:
```
<Label>
  <span>Message</span>
  <Textarea className="mt-1" rows="3" placeholder="Enter some long form content." />
</Label>
```
Note: The default base textarea doesn't need any special prop, but all attributes that you would usually use in normal HTML are available here too. Note that if you're not using a `Label` component (not recommended), you should use an `aria-label` attribute to give screen readers a label.

<h2 id="props-overview" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); margin: 3rem 0px 1rem; font-size: 1.25rem; font-weight: 600; font-family: &quot;Fira Code&quot;, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; position: relative; --text-opacity:1; color: rgba(36,38,45,var(--text-opacity)); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Props overview</h2>

Prop | Description | Type | Default
-- | -- | -- | --
disabled | apply disabled styles to the textarea | boolean |  
invalid | apply invalid styles to the textarea | boolean |  

<h2 id="customizing" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); margin: 3rem 0px 1rem; font-size: 1.25rem; font-weight: 600; font-family: &quot;Fira Code&quot;, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; position: relative; --text-opacity:1; color: rgba(36,38,45,var(--text-opacity)); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a aria-hidden="true" tabindex="-1" href="https://windmillui.com/react-ui/components/textarea#customizing" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); background-color: transparent; color: inherit; text-decoration: inherit; position: absolute;"><span class="icon icon-link" style="box-sizing: border-box; border: 0px solid rgb(213, 214, 215); width: 1rem; height: 1rem; background-image: url(&quot;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='100%' height='100%' fill='none' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' viewBox='0 0 24 24' stroke='currentColor'%3E%3Cpath d='M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1'%3E%3C/path%3E%3C/svg%3E&quot;); background-repeat: no-repeat;"></span></a></h2><br class="Apple-interchange-newline">

**Requirements:** 
- [ ] should be able to import as: 
`import { Textarea } from 'greenhouse-react-ui'`
- [ ] Customisable: User should be able to pass their own class, style or other props ex: `rows` to the element and it should be applied, please have a look at the other existing components to understand how it is done
- [ ] Add unit tests to test the above requirements, please have a look at tests written for other components

**Comment by erandakarachchi** [comment]
Hi @kirandash ,
I would like to work on this if this hasn't been worked already.

**Comment by kirandash** [comment]
> Hi @kirandash ,
> 
> I would like to work on this if this hasn't been worked already.

Hi @erandakarachchi 

Thanks a lot for showing your interest.

If you need any help, you can comment here or reach me on Discord: https://discord.gg/62VR3MMCVm

**Comment by kirandash** [comment]
Thanks a lot for your contribution @erandakarachchi !

**Comment by erandakarachchi** [comment]
I'm really happy to help @kirandash 😀
